### ISSUE TITLE
Can't select git account?

### ISSUE THREAD

**Issue by slient2010** [mbecker20/monitor#10]
I used latest source compiled and tried to use self-hosted git server. but can't select git account. may I know how to set it or where I can set it? Thanks.

BTW, I have set core config.toml like below.

```toml
[[git_provider]]
domain = "git.myselfhosted.dev" # use a custom provider, like self-hosted gitea
accounts = [
	{ username = "mbecker20", token = "access_token_for_account" },
]
```
