### ISSUE TITLE
bug: invalid max and used storage when using docker bind mountpoints

### ISSUE THREAD

**Issue by Lukas-Heiligenbrunner** [mbecker20/monitor#31]
When using docker bind mountpoints every mountpoint shows as device and is added multiple times to the total capacity.
Compose file:

```
version: '3'
services:
  aurcache_dev:
    image: ghcr.io/lukas-heiligenbrunner/aurcache:latest
    ports:
      - "9095:8080"
      - "9096:8081"
    volumes:
      - aurcache_db_dev:/app/db
      - aurcache_repo_dev:/app/repo
      - /var/run/docker.sock:/var/run/docker.sock
      - artifact_cache:/app/builds
    environment:
      - BUILD_ARTIFACT_DIR=artifact_cache # also absolute path is possible
      - LOG_LEVEL=trace
      - MAX_CONCURRENT_BUILDS=2
      - CPU_LIMIT=100
      - MEMORY_LIMIT=-1
    restart: unless-stopped
volumes:
  artifact_cache:
    driver: local
  aurcache_db_dev:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/media/3TBRaid/3TBRaid/Docker/aurcache-dev/db"
  aurcache_repo_dev:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/media/3TBRaid/3TBRaid/Docker/aurcache-dev/repo"
```
![image](https://github.com/user-attachments/assets/b5a6f8f9-980c-43c6-a7cb-48b6c073b0b1)
